format = """
$directory\
$git_branch\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "#B5DFE3"

[git_branch]
style = "#4AB2BF"

[cmd_duration]
style = "#B5DFE3"

[character]
success_symbol = "[❯](#4AB2BF)"
error_symbol = "[❯](#ba0e2e)"